source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'
use_frameworks!

target 'BannerTableViewExample' do
    pod 'Google-Mobile-Ads-SDK'#, '7.32'
    pod 'GoogleMobileAdsMediationMoPub'#, '4.16'
end
